### ISSUE TITLE
return toupper(getche())

### ISSUE THREAD

**Issue by BrunoCerberus** [Catchola/estrutura-dados-a2#4]
Para que retornar char? não é mais fácil com numeros inteiros?

**Comment by lucaslopes** [comment]
Se o usuário digitar algum caractere diferente de numero, não daria problema?

**Comment by BrunoCerberus** [comment]
O grande problema era o toupper(), que serve pra deixar o caractere capturado em maiúsculo, não existe maiúsculo de 1. Removendo ambos não precisamos fazer duas chamadas de funções, apenas o scanf()
